# Generated by Django 3.2.8 on 2021-10-08 19:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_no', models.IntegerField()),
                ('student_name', models.CharField(max_length=30)),
                ('student_dob', models.DateField()),
                ('student_doj', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
