# Generated by Django 3.2.8 on 2021-10-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
